on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t harrytewkesburyit/manual-release -f Dockerfile .
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          application_name: manual-release
          environment_name: Manual-release-env
          existing_bucket_name: elasticbeanstalk-us-east-1-499090944509
          region: us-east-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip